[package]
name = "triland_rust_design_pattern"
version = "0.1.0"
edition = "2021"
authors = ["CestcaVision <tricrepe.nicolas@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
